// Local translation helper for premium Korean experience

export const pokemonKoreanNames: Record<number, string> = {
  1: '이상해씨', 2: '이상해풀', 3: '이상해꽃',
  4: '파이리', 5: '리자드', 6: '리자몽',
  7: '꼬부기', 8: '어니부기', 9: '거북왕',
  10: '캐터피', 11: '단데기', 12: '버터플',
  13: '뿔충이', 14: '딱충이', 15: '독침붕',
  16: '구구', 17: '피죤', 18: '피죤투',
  19: '꼬렛', 20: '레트라',
  21: '깨비참', 22: '깨비드릴조',
  23: '아보', 24: '아보크',
  25: '피카츄', 26: '라이츄',
  27: '모래두지', 28: '고지',
  29: '니드런♀', 30: '니드리나', 31: '니드퀸',
  32: '니드런♂', 33: '니드리노', 34: '니드킹',
  35: '삐삐', 36: '픽시',
  37: '식스테일', 38: '나인테일',
  39: '푸린', 40: '푸크린',
  41: '주뱃', 42: '골뱃',
  43: '뚜벅쵸', 44: '냄새꼬', 45: '라플레시아',
  46: '파라스', 47: '파라섹트',
  48: '콘팡', 49: '도나리',
  50: '디그다', 51: '닥트리오',
  52: '나옹', 53: '페르시온',
  54: '고라파덕', 55: '골덕',
  56: '망키', 57: '성원숭',
  58: '가디', 59: '윈디',
  60: '발챙이', 61: '슈륙챙이', 62: '강챙이',
  63: '캐이시', 64: '윤겔라', 65: '후딘',
  66: '알통몬', 67: '근육몬', 68: '괴력몬',
  69: '모다피', 70: '우츠동', 71: '우츠보트',
  72: '왕눈해', 73: '독파리',
  74: '꼬마돌', 75: '데구리', 76: '딱구리',
  77: '포니타', 78: '날씽마',
  79: '야돈', 80: '야도란',
  81: '코일', 82: '레어코일',
  83: '파오리',
  84: '두두', 85: '두트리오',
  86: '쥬쥬', 87: '쥬레곤',
  88: '질퍽이', 89: '질뻐기',
  90: '셀러', 91: '파르셀',
  92: '고스', 93: '고우스트', 94: '팬텀',
  95: '롱스톤',
  96: '슬리프', 97: '슬리퍼',
  98: '크랩', 99: '킹크랩',
  100: '찌리리공', 101: '붐볼',
  102: '아라리', 103: '나시',
  104: '탕구리', 105: '텅구리',
  106: '시라소몬', 107: '홍수몬',
  108: '내루미',
  109: '또가스', 110: '또도가스',
  111: '뿔카노', 112: '코뿌리',
  113: '럭키',
  114: '덩쿠리',
  115: '캥카',
  116: '쏘드라', 117: '시드라',
  118: '콘치', 119: '왕콘치',
  120: '별가사리', 121: '아쿠스타',
  122: '마임맨',
  123: '스라크',
  124: '루주라',
  125: '에레브',
  126: '마그마',
  127: '쁘사이저',
  128: '켄타로스',
  129: '잉어킹', 130: '갸라도스',
  131: '라프라스',
  132: '메타몽',
  133: '이브이', 134: '샤미드', 135: '쥬피썬더', 136: '부스터',
  137: '폴리곤',
  138: '암나이트', 139: '암스타',
  140: '투구', 141: '투구푸스',
  142: '프테라',
  143: '잠만보',
  144: '프리져', 145: '썬더', 146: '파이어',
  147: '미뇽', 148: '신뇽', 149: '망나뇽',
  150: '뮤츠', 151: '뮤',
  152: '치코리타', 153: '베이리프', 154: '메가니움',
  155: '브케인', 156: '마그케인', 157: '블레이범',
  158: '리아코', 159: '엘리게이', 160: '장크로다일',
  161: '꼬리선', 162: '다꼬리', 163: '부부', 164: '야부엉',
  165: '레디바', 166: '레디안', 167: '페이검', 168: '아리아도스',
  169: '크로뱃', 170: '초라기', 171: '랜턴', 172: '피츄',
  173: '삐', 174: '푸푸린', 175: '토게피', 176: '토게틱',
  177: '네이티', 178: '네이티오', 179: '메리프', 180: '보송송',
  181: '전룡', 182: '아르코', 183: '마릴', 184: '마릴리',
  185: '꼬지모', 186: '왕구리', 187: '통통코', 188: '두코',
  189: '솜솜코', 190: '에이팜', 191: '해너츠', 192: '해루미',
  193: '왕자리', 194: '우파', 195: '누오', 196: '에브이',
  197: '블래키', 198: '니로우', 199: '야도킹', 200: '무우마',
  201: '안농', 202: '마자용', 203: '키링키', 204: '피콘',
  205: '쏘콘', 206: '노고치', 207: '글라이거', 208: '강철톤',
  209: '블루', 210: '그랑블루', 211: '침바루', 212: '핫삼',
  213: '단단지', 214: '헤라크로스', 215: '포푸니', 216: '깜지곰',
  217: '링곰', 218: '마그마그', 219: '마그카르고', 220: '꾸꾸리',
  221: '메꾸리', 222: '코산호', 223: '총어', 224: '대포무노',
  225: '딜리버드', 226: '만타인', 227: '무장조', 228: '델빌',
  229: '헬가', 230: '킹드라', 231: '코코리', 232: '코리갑',
  233: '폴리곤2', 234: '노라키', 235: '루브도', 236: '배루키',
  237: '카포에라', 238: '뽀뽀라', 239: '에레키드', 240: '마그비',
  241: '밀탱크', 242: '해피너스', 243: '라이코', 244: '앤테이',
  245: '스이쿤', 246: '애버라스', 247: '데기라스', 248: '마기라스',
  249: '루기아', 250: '칠색조', 251: '세레비'
};

export const pokemonTypeTranslations: Record<string, string> = {
  normal: '노멀', fire: '불꽃', water: '물', grass: '풀',
  electric: '전기', ice: '얼음', fighting: '격투', poison: '독',
  ground: '땅', flying: '비행', psychic: '에스퍼', bug: '벌레',
  rock: '바위', ghost: '고스트', dragon: '드래곤', dark: '악',
  steel: '강철', fairy: '페어리'
};

export const pokemonMoveTranslations: Record<string, string> = {
  tackle: '몸통박치기', 'scratch': '할퀴기', 'pound': '막치기',
  'gust': '바람일으키기', 'wing-attack': '날개치기', 'fly': '공중날기',
  'double-slap': '연속뺨치기', 'mega-punch': '메가톤펀치', 'fire-punch': '불꽃펀치',
  'ice-punch': '번개펀치', 'thunder-punch': '번개펀치', 'scratch-cat-attack': '고양이돈받기',
  'swords-dance': '칼춤', 'cut': '풀베기', 'vine-whip': '덩굴채찍',
  'mega-drain': '메가드레인', 'solar-beam': '솔라빔', 'poison-powder': '독가루',
  'stun-spore': '저리어포자', 'sleep-powder': '수면가루', 'petal-dance': '꽃잎댄스',
  'string-shot': '실뿜기', 'dragon-rage': '용의분노', 'fire-spin': '회오리불꽃',
  'ember': '불꽃세례', 'flamethrower': '화염방사', 'water-gun': '물대포',
  'hydro-pump': '하이드로펌프', 'surf': '파도타기', 'ice-beam': '냉동빔',
  'blizzard': '눈보라', 'psybeam': '환상빔', 'bubble-beam': '거품광선',
  'aurora-beam': '오로라빔', 'hyper-beam': '파괴광선', 'peck': '쪼기',
  'drill-peck': '회전부리', 'submission': '지옥바퀴', 'low-kick': '안안다리걸기',
  'counter': '카운터', 'seismic-toss': '지구던지기', 'strength': '괴력',
  'absorb': '흡수', 'mega-gain': '메가드레인', 'growth': '성장',
  'leech-seed': '씨뿌리기', 'razor-leaf': '잎날가르기', 'earthquake': '지진',
  'fissure': '구멍파기', 'dig': '구멍파기', 'toxic': '맹독',
  'confusion': '염동력', 'psychic': '사이코키네시스', 'hypnosis': '최면술',
  'meditate': '명상', 'agility': '고속이동', 'quick-attack': '전광석화',
  'rage': '분노', 'teleport': '순간이동', 'night-shade': '나이트헤드',
  'mimic': '흉내내기', 'screech': '싫은소리', 'double-team': '그림자분신',
  'recover': '태만함', 'harden': '단단해지기', 'minimize': '작아지기',
  'smokescreen': '연막', 'confuse-ray': '이상한빛', 'withdraw': '껍질에숨기',
  'defense-curl': '웅크리기', 'barrier': '장막', 'light-screen': '빛의장막',
  'haze': '안개제거', 'reflect': '리플렉터', 'focus-energy': '기충전',
  'bide': '참기', 'metronome': '손가락흔들기', 'mirror-move': '따라하기',
  'self-destruct': '자폭', 'egg-bomb': '알폭탄', 'lick': '핥기',
  'smog': '스모그', 'sludge': '오물공격', 'bone-club': '뼈다귀치기',
  'fire-blast': '불대포', 'waterfall': '폭포오르기', 'clamp': '껍질끼우기',
  'swift': '스피드스타', 'skull-bash': '로켓박치기', 'spike-cannon': '가시캐논',
  'constrict': '똬리틀기', 'amnesia': '망각술', 'kinesis': '숟가락꺾기',
  'soft-boiled': '알낳기', 'hi-jump-kick': '무릎차기', 'glare': '뱀눈초리',
  'dream-eater': '꿈먹기', 'poison-gas': '독가스', 'barrage': '알폭탄',
  'leech-life': '흡혈', 'lovely-kiss': '악마의키스', 'sky-attack': '불새',
  'transform': '변신', 'bubble': '거품', 'dizzy-punch': '피요피요펀치',
  'spore': '버섯포자', 'flash': '플래시', 'psywave': '사이코웨이브',
  'splash': '튀어오르기', 'acid-armor': '녹기', 'crabhammer': '집게해머',
  'explosion': '대폭발', 'fury-swipes': '마구할퀴기', 'bonemerang': '본메랑',
  'rest': '잠자기', 'rock-slide': '스톤샤워', 'hyper-fang': '필살앞니',
  'sharpen': '각지기', 'conversion': '텍스처', 'tri-attack': '트라이어택',
  'super-fang': '분노의앞니', 'slash': '베어가르기', 'substitute': '대역',
  'struggle': '발버둥', 'thunder': '번개', 'thunderbolt': '10만볼트',
  'thunder-shock': '전기쇼크', 'thunder-wave': '전기자석파',
  'rock-throw': '돌뿌리기', 'headbutt': '박치기', 'bite': '물기',
  'flame-wheel': '바퀴벌레', 'iron-tail': '아이언테일', 'giga-drain': '기가드레인',
  'shadow-ball': '섀도볼', 'sludge-bomb': '오물폭탄', 'signal-beam': '시그널빔'
};

export const getPokemonKoreanName = (id: number, fallback: string): string => {
  return pokemonKoreanNames[id] || fallback;
};

export const getTypeNameKorean = (type: string): string => {
  return pokemonTypeTranslations[type.toLowerCase()] || type;
};

export const getMoveNameKorean = (name: string): string => {
  const cleanKey = name.toLowerCase().replace(' ', '-');
  return pokemonMoveTranslations[cleanKey] || name;
};
